SchedulerMVC/Models/Plan.cs
using System;

namespace SchedulerMVC.Models
{
    public class Plan
    {
        public int Id { get; set; }
        public string Note { get; set; }
        public DateTime Date { get; set; }
    }
}

SchedulerMVC/Models/PlanContext.cs
using System.Data.Entity;

namespace SchedulerMVC.Models
{
    public class PlanContext : DbContext
    {
        public DbSet<Plan> Plans { get; set; }
    }
}

SchedulerMVC/Controllers/PlansController.cs
using SchedulerMVC.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace SchedulerMVC.Controllers
{
    public class PlansController : Controller
    {
        private PlanContext db = new PlanContext();

        public ActionResult AllNote(string searchNote)
        {
            var plans = from m in db.Plans
                select m;

            if (!String.IsNullOrEmpty(searchNote))
            {
                plans = plans.Where(s => s.Note.Contains(searchNote));
            }

            return View(plans);
        }

        public ActionResult OverdueIndex()
        {
            return View(db.Plans.Where(t => t.Date < DateTime.Today).ToList());
        }

        
        public ActionResult TomorrowIndex()
        {
            var tommorrowDate = DateTime.Today.AddDays(1);

            return View(db.Plans.Where(t => t.Date == tommorrowDate).ToList());
        }

        
        public ActionResult TodayIndex()
        {
            return View(db.Plans.Where(t => t.Date == DateTime.Today).ToList());
        }

        
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Plan plan = db.Plans.Find(id);
        //    if (plan == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(plan);
        //}

        
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        
        public ActionResult Create([Bind(Include = "Id,Note,Date")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                db.Plans.Add(plan);
                db.SaveChanges();
                return RedirectToAction("AllNote");
            }

            return View(plan);
        }

        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plan plan = db.Plans.Find(id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }

        
        [HttpPost]
        
        public ActionResult Edit([Bind(Include = "Id,Note,Date")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(plan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AllNote");
            }
            return View(plan);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plan plan = db.Plans.Find(id);
            if (plan == null)
            {
                return HttpNotFound();
            }
            return View(plan);
        }


        [HttpPost, ActionName("Delete")]

        public ActionResult Delete(int id)
        {
            Plan plan = db.Plans.Find(id);
            db.Plans.Remove(plan);
            db.SaveChanges();
            return RedirectToAction("AllNote");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchedulerMVC/Views/Plans/AllNote.cshtml
@model IEnumerable<SchedulerMVC.Models.Plan>

@{
    ViewBag.Title = "AllNote";
}

<h2>Список заметок</h2>

<form asp-controller="Plans" asp-action="AllNote">
    <p>
        Note: <input type="text" name="searchNote" placeholder="Поиск">
        <input type="submit" value="Поиск" class="btn btn-default"/>
    </p>
</form>

<table class="table table-striped">
    <tr>
        <th>
            Note
        </th>
        <th>
            Date
        </th>
        <td></td>
    </tr>
    @if (Model.ToList().Count == 0 || Model.ToList() == null)
    {
        <tr>
            <td class="text-muted font-weight-lighter" colspan="3" style="text-align: center">Список пуст</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td class="notewidth">
                    @item.Note
                </td>
                <td>
                    @item.Date.ToShortDateString()
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Plans", new { id = item.Id })" type="button" class="btn btn-default">Редактировать</a>
                    <a href="@Url.Action("Delete", "Plans", new { id = item.Id })" type="button" class="btn btn-default">Удалить</a>
                </td>
            </tr>
        }
    }
</table>

SchedulerMVC/Views/Plans/Create.cshtml
@model SchedulerMVC.Models.Plan

@{
    ViewBag.Title = "Create";
}

<h2>Создание новой заметки</h2>


@using (Html.BeginForm()) 
{
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        <div class="text-danger" data-valmsg-summary="true"></div>
        <div class="form-group">
            <label for="Note" class="control-label col-md-2">Note</label>
            <div class="col-md-10">
                <textarea class="text-area text-box single-line input-validation-error" data-val="true" data-val-required="Пожалуйста введите заметку." 
                          id="Note" name="Note" value aria-describedby="Note-error" aria-invalid="true" ></textarea>
                <span class="text-danger field-validation-error" data-valmsg-for="Note" data-valmsg-replace="true"></span>
            </div>
        </div>


        <div class="form-group">
            <label for="Date" class="control-label col-md-2">Date</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line input-validation-error datewidth" data-val="true" data-val-required="Пожалуйста введите дату."
                       id="Date" name="Date" type="date" aria-describedby="Date-error" aria-invalid="true">
                <span class="text-danger field-validation-error" data-valmsg-for="Date" data-valmsg-replace="true"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
                <a href="/Plans/AllNote" type="button" class="btn btn-default">Вернутся к списку</a>
            </div>
        </div>

    </div>
}
<hr />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchedulerMVC/Views/Plans/Delete.cshtml
@model SchedulerMVC.Models.Plan

@{
    ViewBag.Title = "Delete";
}

<h3>Вы действительно хотите удалить эту заметку?</h3>
<div>
    <h4></h4>
    <hr />
    <dl>
        <dt class="deleteDt">
            Note
        </dt>
        <dd class="notewidth deleteDd">
            @Model.Note
        </dd>
        <dt class="deleteDt">
            Date
        </dt>
        <dd class="deleteDd">
            @Model.Date.ToShortDateString()
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        <div style="margin-left: 120px">
            <input type="submit" value="Удалить" class="btn btn-default" />
            <a href="/Plans/AllNote" type="button" class="btn btn-default">Вернутся к списку</a>
        </div>
    }
    <hr />
</div>

SchedulerMVC/Views/Plans/Details.cshtml
@model SchedulerMVC.Models.Plan

@{
    ViewBag.Title = "Details";
}

<h2>Описание заметки</h2>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Note
        </dt>

        <dd class="notewidth">
            @Model.Note
        </dd>

        <dt>
            Date
        </dt>

        <dd>
            @Model.Date.ToShortDateString()
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Вернуться к списку", "AllNote")
</p>
<hr />

SchedulerMVC/Views/Plans/Edit.cshtml
@model SchedulerMVC.Models.Plan

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование заметки</h2>


@using (Html.BeginForm())
{
    
<div class="form-horizontal">
    <h4></h4>
    <hr />
    <div class="text-danger" data-valmsg-summary="true"></div>
    <div class="form-group">
        <label for="Note" class="control-label col-md-2">Note</label>
        <div class="col-md-10">
            
            <textarea class="text-area text-box single-line input-validation-error" data-val="true" data-val-required="Пожалуйста введите заметку." 
                          id="Note" name="Note" value aria-describedby="Note-error" aria-invalid="true">@Model.Note</textarea>
            <span class="text-danger field-validation-error" data-valmsg-for="Note" data-valmsg-replace="true"></span>
        </div>
    </div>

    <div class="form-group">
        <label for="Date" class="control-label col-md-2">Date</label>
        <div class="col-md-10">
            <input class="form-control text-box single-line input-validation-error datewidth" data-val="true" data-val-required="Пожалуйста введите дату."
                   id="Date" name="Date" type="date" aria-describedby="Date-error" aria-invalid="true">
            <span class="text-danger field-validation-error" data-valmsg-for="Date" data-valmsg-replace="true"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
            <a href="/Plans/AllNote" type="button" class="btn btn-default">Вернутся к списку</a>
        </div>
    </div>
</div>
}
<hr />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchedulerMVC/Views/Plans/OverdueIndex.cshtml
@model IEnumerable<SchedulerMVC.Models.Plan>

@{
    ViewBag.Title = "OverdueIndex";
}

<h2>Просроченные заметки</h2>

<table class="table table-striped">
    <tr>
        <th>
            Note
        </th>
        <th>
            Date
        </th>
        <th></th>
    </tr>
    @if (Model.ToList().Count == 0 || Model.ToList() == null)
    {
        <tr>
            <td class="text-muted font-weight-lighter" colspan="3" style="text-align: center">Список пуст</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td class="notewidth">
                    @item.Note
                </td>
                <td>
                    @item.Date.ToShortDateString()
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Plans", new { id = item.Id })" type="button" class="btn btn-default">Редактировать</a>
                    <a href="@Url.Action("Delete", "Plans", new { id = item.Id })" type="button" class="btn btn-default">Удалить</a>
                </td>
            </tr>
        }
    }
</table>

SchedulerMVC/Views/Plans/TodayIndex.cshtml
@model IEnumerable<SchedulerMVC.Models.Plan>

@{
    ViewBag.Title = "TodayNote";
}

<h2>Сегодняшние заметки</h2>

<table class="table table-striped">
    <tr>
        <th>
            Note
        </th>
        <th>
            Date
        </th>
        <th></th>
    </tr>
    @if (Model.ToList().Count == 0 || Model.ToList() == null)
    {
        <tr>
            <td class="text-muted font-weight-lighter" colspan="3" style="text-align: center">Список пуст</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td class="notewidth">
                    @item.Note
                </td>
                <td>
                    @item.Date.ToShortDateString()
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Plans", new { id = item.Id })" type="button" class="btn btn-default">Редактировать</a>
                    <a href="@Url.Action("Delete", "Plans", new { id = item.Id })" type="button" class="btn btn-default">Удалить</a>
                </td>
            </tr>
        }
    }

</table>

SchedulerMVC/Views/Plans/TomorrowIndex.cshtml
@model IEnumerable<SchedulerMVC.Models.Plan>

@{
    ViewBag.Title = "TomorrowIndex";
}

<h2>Завтрашние заметки</h2>

<table class="table table-striped">
    <tr>
        <th>
            Note
        </th>
        <th>
            Date
        </th>
        <th></th>
    </tr>
    @if (Model.ToList().Count == 0 || Model.ToList() == null)
    {
        <tr>
            <td class="text-muted font-weight-lighter" colspan="3" style="text-align: center">Список пуст</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td class="notewidth">
                    @item.Note
                </td>
                <td>
                    @item.Date.ToShortDateString()
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Plans", new { id = item.Id })" type="button" class="btn btn-default">Редактировать</a>
                    <a href="@Url.Action("Delete", "Plans", new { id = item.Id })" type="button" class="btn btn-default">Удалить</a>
                </td>
            </tr>
        }
    }
</table>

SchedulerMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="/Content/Style.css" rel="stylesheet" />
    <link href="/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Список заметок", "AllNote", "Plans", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Заметки на сегодня", "TodayIndex", "Plans")</li>
                    <li>@Html.ActionLink("Заметки на завтра", "TomorrowIndex", "Plans")</li>
                    <li>@Html.ActionLink("Просроченные заметки", "OverdueIndex", "Plans")</li>
                    <li>@Html.ActionLink("Создать новую заметку", "Create", "Plans")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>